export const DEFAULT_MUGSHOTS = {
  mugshot1: "/src/assets/images/mugshot_1_1783534736104.jpg",
  mugshot2: "/src/assets/images/mugshot_2_1783534747660.jpg",
  mugshot3: "/src/assets/images/mugshot_3_1783534760116.jpg",
  mugshot4: "/src/assets/images/mugshot_4_1783534771722.jpg",
};

export const MOCK_SUSPECTS = [
  {
    id: "susp-001",
    name: "Carlos Eduardo Silva",
    alias: "Cadu",
    document: "38.941.284-9 (RG)",
    status: "wanted" as const,
    birthDate: "1992-04-12",
    motherName: "Maria das Dores Silva",
    faction: "Comando Vermelho (CV)",
    areaOfOperation: "Complexo da Penha, Rio de Janeiro - RJ",
    height: "1.78m",
    weight: "82kg",
    skinColor: "Parda",
    eyeColor: "Castanhos",
    hairType: "Preto, curto e crespo",
    tattoosScars: "Tatuagem de carpa no braço direito, cicatriz linear na bochecha esquerda.",
    observations: "Indivíduo de alta periculosidade, envolvido em roubo de cargas e tráfico de entorpecentes. Mandado de prisão em aberto expedido pela Vara de Execuções Penais.",
    photos: [DEFAULT_MUGSHOTS.mugshot1],
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "susp-002",
    name: "Mariana Souza Santos",
    alias: "Marizinha",
    document: "128.495.230-01 (CPF)",
    status: "investigating" as const,
    birthDate: "1998-09-22",
    motherName: "Ana Souza Santos",
    faction: "Primeiro Comando da Capital (PCC)",
    areaOfOperation: "Zona Sul, São Paulo - SP",
    height: "1.65m",
    weight: "58kg",
    skinColor: "Branca",
    eyeColor: "Verdes",
    hairType: "Loiro, longo e liso",
    tattoosScars: "Pequena tatuagem de borboleta atrás da orelha direita.",
    observations: "Investigada por atuar na lavagem de dinheiro da organização criminosa através de empresas de fachada. Monitorada em escutas telefônicas autorizadas.",
    photos: [DEFAULT_MUGSHOTS.mugshot2],
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "susp-003",
    name: "Rodrigo Alencar Barbosa",
    alias: "Diguinho",
    document: "4.921.801 (RG)",
    status: "arrested" as const,
    birthDate: "1984-01-30",
    motherName: "Helena Alencar Barbosa",
    faction: "Milícia Liga da Justiça",
    areaOfOperation: "Campo Grande, Rio de Janeiro - RJ",
    height: "1.82m",
    weight: "95kg",
    skinColor: "Branca",
    eyeColor: "Castanhos",
    hairType: "Cabelo curto, castanho, calvície frontal",
    tattoosScars: "Cicatriz cirúrgica no ombro esquerdo. Sem tatuagens aparentes.",
    observations: "Ex-policial militar expulso da corporação. Preso em operação recente contra extorsão armada a comerciantes e controle ilegal de serviços de internet/gás.",
    photos: [DEFAULT_MUGSHOTS.mugshot3],
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "susp-004",
    name: "Juliana Mendes Ferreira",
    alias: "Jú da Leste",
    document: "50.129.842-X (RG)",
    status: "inactive" as const,
    birthDate: "1991-11-05",
    motherName: "Sônia Mendes Ferreira",
    faction: "Independente",
    areaOfOperation: "Zona Leste, Belo Horizonte - MG",
    height: "1.70m",
    weight: "64kg",
    skinColor: "Parda",
    eyeColor: "Castanhos escuros",
    hairType: "Preto, liso, na altura dos ombros",
    tattoosScars: "Tatuagem de flor de lótus nas costas.",
    observations: "Histórico de estelionato e clonagem de cartões de crédito. Atualmente em regime aberto, cumprindo medidas cautelares e sem novas ocorrências registradas.",
    photos: [DEFAULT_MUGSHOTS.mugshot4],
    createdBy: "system",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const MOCK_OCCURRENCES = [
  {
    id: "DE81YBYCS",
    title: "AMEAÇA - VIAS DE FATO",
    description: "A guarnição composta pelo Sgt PM Hammes e SD PM Severo foi despachada via Sala de Operações para averiguar situação de possível ameaça envolvendo aluno e professora em ambiente escolar.\nNo local, foi realizado contato com a diretora Betina Zoleica Mallmann Immich, RG nº 1042856599, com a professora Isabel Cristina Becker Delwing Masiero, RG nº 8062524148, com a mãe do aluno, Chana Cristina Wolff, CPF nº 02263981020, e com o aluno Kayê Wolff da Silva, CPF: 06481808081.\n\nConforme os relatos colhidos no local, teria ocorrido uma discussão envolvendo o aluno e a professora, sendo informado ainda que, durante o desentendimento, o aluno fez ameaças de agredir a professora em via pública.",
    location: "RUA ETWINO THEOBALDO THOMAS, 1300 - PLANALTO, LAJEADO - RS",
    date: "2026-08-12",
    time: "14:30",
    severity: "high" as const,
    status: "investigating" as const,
    envolvidoName: "KAYÊ WOLFF DA SILVA",
    vulgo: "N/I",
    alvosCount: 2,
    hasMaterial: false,
    photoUrl: DEFAULT_MUGSHOTS.mugshot1,
    photos: [DEFAULT_MUGSHOTS.mugshot1, DEFAULT_MUGSHOTS.mugshot2],
    involvedPeople: [
      { id: "p-1", name: "KAYÊ WOLFF DA SILVA", vulgo: "N/I", document: "Doc: 4145435238", photoUrl: DEFAULT_MUGSHOTS.mugshot1 },
      { id: "p-2", name: "ISABEL CRISTINA BECKER DELWING MASIERO", vulgo: "N/I", document: "Doc: 8062524148", photoUrl: DEFAULT_MUGSHOTS.mugshot2 }
    ],
    agentInCharge: "Sgt PM Hammes",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "G010CKBU4",
    title: "CUMPRIMENTO DE MANDADO JUDICIAL DE...",
    description: "Abordagem tática para cumprimento de mandado expedido pela comarca local.",
    location: "LAJEADO • RUA AIRTON CESAR, N° 48, BAIRRO CONVENTOS, LAJEADO.",
    date: "2026-08-12",
    time: "10:15",
    severity: "critical" as const,
    status: "open" as const,
    envolvidoName: "CAUA RENATO STEFFLER",
    alvosCount: 1,
    hasMaterial: false,
    photoUrl: DEFAULT_MUGSHOTS.mugshot2,
    agentInCharge: "Agente Santos",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "EY9FAAPST",
    title: "APREENSÃO DE OBJETO",
    description: "Apreensão de objetos ilícitos e materiais suspeitos durante averiguação.",
    location: "LAJEADO • RUA IRMÃO EMÍLIO CONRADO, N° 668 , BAIRRO MOINHOS, LAJEADO.",
    date: "2026-08-12",
    time: "16:20",
    severity: "medium" as const,
    status: "investigating" as const,
    envolvidoName: "ADRIANO DA SILVA",
    vulgo: "NENE",
    alvosCount: 2,
    hasMaterial: true,
    extraPhotosCount: 1,
    photoUrl: DEFAULT_MUGSHOTS.mugshot3,
    agentInCharge: "Sgt. Oliveira",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "YA74OMT8Z",
    title: "CUMPRIMENTO DE MANDADO DE PRISÃO.",
    description: "Prisão preventiva executada com sucesso sem alteração da ordem pública.",
    location: "• RUA CECÍLIA CATARINA SULZBACH, 295 - SANTO ANDRÉ, LAJEADO.",
    date: "2026-08-11",
    time: "08:45",
    severity: "critical" as const,
    status: "closed" as const,
    envolvidoName: "RODRIGO DE FREITAS",
    alvosCount: 1,
    hasMaterial: false,
    photoUrl: DEFAULT_MUGSHOTS.mugshot4,
    agentInCharge: "Det. Albuquerque",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "HRCTKV6XJ",
    title: "VIOLÊNCIA DOMÉSTICA (AMEAÇA E RESIS...",
    description: "Ocorrência de violência doméstica com desobediência e resistência no local.",
    location: "LAJEADO • RUA EQUADOR, 50, BAIRRO NAÇÕES – LAJEADO/RS",
    date: "2026-08-10",
    time: "22:10",
    severity: "high" as const,
    status: "investigating" as const,
    envolvidoName: "ALISSON MARLON DOS SANTOS",
    alvosCount: 2,
    hasMaterial: false,
    photoUrl: DEFAULT_MUGSHOTS.mugshot1,
    agentInCharge: "Agente Silva",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "3XCZIMUMW",
    title: "VIAS DE FATO E AMEAÇA",
    description: "Desentendimento com agressões verbais e físico em via pública.",
    location: "LAJEADO • RUA CARLOS SPOHR FILHO - 4045 - MOINHOS D'ÁGUA - LAJEADO",
    date: "2026-08-10",
    time: "19:30",
    severity: "medium" as const,
    status: "open" as const,
    envolvidoName: "ARI ELVES SANTOS PEREIRA",
    vulgo: "ELVES",
    alvosCount: 2,
    hasMaterial: false,
    photoUrl: DEFAULT_MUGSHOTS.mugshot2,
    agentInCharge: "Agente Pereira",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "KNKDT53HF",
    title: "AMEAÇA DE MORTE",
    description: "Ameaça direta e tentativa de intimidação relatada por testemunhas.",
    location: "LAJEADO • RUA 7 DE SETEMBRO - 130 - FLORESTAL - LAJEADO",
    date: "2026-08-09",
    time: "11:00",
    severity: "high" as const,
    status: "investigating" as const,
    envolvidoName: "CHARLES DE OLIVEIRA",
    vulgo: "PITOCO",
    alvosCount: 2,
    hasMaterial: false,
    photoUrl: DEFAULT_MUGSHOTS.mugshot3,
    agentInCharge: "Agente Santos",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "MU7JAN6Z",
    title: "LESÃO CORPORAL",
    description: "Conflito interpessoal com lesões corporais leves atestadas.",
    location: "ARROIO DO MEIO • RUA MARECHAL FLORIANO PEIXOTO, N° 1648, SÃO JOSÉ, ARROIO DO MEIO-RS",
    date: "2026-08-09",
    time: "15:20",
    severity: "medium" as const,
    status: "open" as const,
    envolvidoName: "CRISTIAN LAWALL KARLINSKI",
    alvosCount: 2,
    hasMaterial: false,
    photoUrl: DEFAULT_MUGSHOTS.mugshot4,
    agentInCharge: "Agente Medeiros",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "8AW3JM1FQ",
    title: "DIFAMAÇÃO",
    description: "Registro de ocorrência por ofensas e injúria em ambiente comunitário.",
    location: "POUSO NOVO • LOCALIDADE DE AMEDOREMA - INTERIOR - POUSO NOVO",
    date: "2026-08-09",
    time: "17:40",
    severity: "low" as const,
    status: "closed" as const,
    envolvidoName: "MARCOS ALBERTON",
    vulgo: "MEDOREMA",
    alvosCount: 2,
    hasMaterial: false,
    photoUrl: DEFAULT_MUGSHOTS.mugshot1,
    agentInCharge: "Agente Silva",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "IF2EBY86",
    title: "LESÃO CORPORAL",
    description: "Agressão física em estabelecimento comercial com lavratura de termo.",
    location: "COQUEIRO BAIXO • LINHA COQUEIRO ALTO, INTERIOR, COQUEIRO BAIXO",
    date: "2026-08-09",
    time: "21:05",
    severity: "high" as const,
    status: "investigating" as const,
    envolvidoName: "VILMAR ANTONIO DE MELLO",
    alvosCount: 3,
    hasMaterial: false,
    photoUrl: DEFAULT_MUGSHOTS.mugshot2,
    agentInCharge: "Agente Oliveira",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

